name: check-alerts
on:
  workflow_dispatch:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install firebase-admin axios
      - name: Run script
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: node index.js
